# Generated by Django 3.2.3 on 2021-05-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
